export enum API_END_POINTS {
  // User Routes
  LOGIN,
  LOGOUT,
  REGISTER,
  READ_USER,
  READ_ORDER,
  READ_ORDERS,
  READ_PRODUCT,
  CREATE_ORDER,
  READ_DOWNLOAD,
  READ_PRODUCTS,
  UPDATE_PRODUCT,
  // Admin Routes
  LOGIN_ADMIN,
  READ_ORDERS_ADMIN,
  UPLOAD_FILES_ADMIN,
  DELETE_FILES_ADMIN,
  UPDATE_PRODUCT_ADMIN,
  GET_MEDIA_LIBRARY_ADMIN
}
